### ISSUE TITLE
Issue with go get -u github.com/microsoftgraph/msgraph-sdk-go

### ISSUE THREAD

**Issue by Blackra1n5** [microsoftgraph/msgraph-sdk-go#101]
I'm brand new to go an and might be completely my own fault but getting this error when running
`go get -u github.com/microsoftgraph/msgraph-sdk-go`
with this error 
```
# github.com/microsoftgraph/msgraph-sdk-go-core
../pkg/mod/github.com/microsoftgraph/msgraph-sdk-go-core@v0.11.0/page_iterator.go:147:47: cannot use *requestInfo (type abstractions.RequestInformation) as type *abstractions.RequestInformation in argument to pI.reqAdapter.NetHttpRequestAdapter.SendAsync
```

Only getting this error on PopOS and not Mac

**Comment by baywet** [comment]
Hi @Blackra1n5 
Thank you for trying the Go SDK and thanks for reaching out.
Are you running this command on a brand new project or on an existing project that already had a reference to the SDK?
If the former, it's stranger that the command is not using the latest version of the SDK.

Can you try running the following command and see whether it works better?

```bash
go get -u github.com/microsoftgraph/msgraph-sdk-go@v0.13.0
```

**Comment by baywet** [comment]
actually after some more investigation into the issue, it looks the issue is caused by the -u switch and the accidental release of a v0.11.0 version of core. I've put together [a PR to retract that version](https://github.com/microsoftgraph/msgraph-sdk-go-core/pull/54) and in the mean time you should be able to get around the issue by running the command I previously shared without the -u switch.
