### ISSUE TITLE
principal "displayName" not published anymore by DirectoryObjects().GetByIds()

### ISSUE THREAD

**Issue by mblaschke** [microsoftgraph/msgraph-sdk-go#209]
It seems that additionalData doesn't publish "displayName" anymore.

Tested with v0.28.0, it was working with v0.26.0

**Comment by mblaschke** [comment]
Thanks, it works with latest version.

This was a little bit unexpected how to access user/group/app information here.
I was expecting something like `DirectoryObjectable.GetUser()` which returns the user object and `nil` if it is something lese.

**Comment by baywet** [comment]
Great! I'm not sure I understand the last part of the comment. Are you suggesting something is missing in the sdk?

**Comment by mblaschke** [comment]
i would prefer something like:

```go
myDirectoryObjects, err := client.DirectoryObjects().GetByIds().Post(payload)

for _, directoryObject := range myDirectoryObjects {
  if user := directoryObject.GetUser(); user != nil {
    // object ist user
   user.GetDisplayName()
  } else if group := directoryObject.GetGroup(); group != nil {
    // object is group
    group.GetDisplayName()
  } else if application := directoryObject.GetApplication(); application != nil {
    // object is app
    application.GetDisplayName()
  }
}
```

this gives you as SDK developer to change the returning struct. i get feedback in the IDE for all the changes.

when using type assertions this gives me as user of the SDK just a bad feeling about future changes which i have to track for every major version because I dont get feedback from golang or my IDE.

what if a pointer is returned? so do i have to add something like that to be future proof?
```go
myDirectoryObjects, err := client.DirectoryObjects().GetByIds().Post(payload)
myDirectoryObject := myDirectoryObjects[0]
if myUser, ok := myDirectoryObject.(models.Userable); ok {
    myUser.GetDisplayName()
}

if myUser, ok := myDirectoryObject.(*models.Userable); ok {
    myUser.GetDisplayName()
}
```

and which object types can be returned here? i have to read the documentation at that point instead of using my IDE.

before i was using (because i was not aware how the SDK is working here so please don't blame me for this ugly piece of code):
```go
myDirectoryObjects, err := client.DirectoryObjects().GetByIds().Post(payload)

for _, directoryObject := range myDirectoryObjects {
   objectData := row.GetAdditionalData()
   // [...]
   if alternativeNames, ok := objectData["alternativeNames"].([]*jsonserialization.JsonParseNode); ok {
     // [...]
   }
}
```

this worked until an update bacause jsonserialization was changed from `github.com/microsoft/kiota/serialization/go/json` to `github.com/microsoft/kiota-serialization-json-go`
I don't got any feedback from my IDE about that change so it was very difficult to identify the issue.

i would love not to use type assumptions when using the SDK because it's resolved on runtime than on compile time.

**Comment by dadams39** [comment]
@mblaschke I am also in the process of looking at testing when it comes to the feature/library changes. I'm not certain about all the IDE's, but I will say that I use a similar check the following:
```go
response, ok := client.Users.GetWithRequestConfigurationAndResponseHandler(options, nil)
```
This lets me know whether some aspects of the code have changed from version to version, but it is far from being comprehensive. From these experiences, I have learned some helpful things from trying to uncover the impact of versioning changes. 
For the most part, I've observed the following pattern for digesting queries or responses from the M365 backstore all look a bit similar to this without using an iterator. So, in my example above, the response is actually a
`response models.UserCollectionResponseable` rather than a user and a little unpacking is required. 
```
for  _, item := range response.GetValue() /// This is a models.Userable item and the next line would not be required.
user, ok := item.(models.Userable)
aPointer := user.GetDisplayName()
```
Kiota is a generator that tries to standardize the output across the SDK. So, while I am not talking specifically about Directory objects, Many of the GetVarName() calls will point to a pointer of a certain type. The `GetAdditionalData()` returns a `map[string]interface` which you can see in the documentation in `msgraph-sdk-go/models/entity.go` which is the base for a huge majority of the items in the **models** package.  

As a practice, there will be glitches when it comes to basing functionality on `AdditionalData` as it can holds data that could not be placed into the struct fields during the `CreateFromDiscriminatorValue` call.

Each model should have an `able`-named interface that can be corresponded with In the case of the -> `directory_object` `directory_objectable` and it will list the calls that can be relied on and the change of these calls should give an error on most IDEs. 

```go
type DirectoryObjectable interface {
    Entityable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDeletedDateTime()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    SetDeletedDateTime(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
}
```
Any calls outside of these interfaces are not guaranteed to be supported. And while the `GetAdditionalValues()` is guaranteed to be supported, the values within the map are not guaranteed to be there from version to version. 

I hope that was of some use.

**Comment by mblaschke** [comment]
@dadams39 
Thanks for explanation, I'm just wondering about the different styles how these SDKs are working as I'm a primary user of the Azure SDK and Kubernetes SDK.

The msgraph-sdk-go is sometimes surprising and I had more problems when updating it then I had when switching from old Azure SDK to the new one or when updating Kubernetes SDK. I'm aware that this sdk is not finished yet so I only can give my view from a user/developer perspective as I'm happy that there is a SDK for msgraph available which is needed for several Azure applications.

In Azure/Kubernetes SDK i normally don't have to use type assertions which makes it easier and more future proof (the reason I really love golang over other languages even if it's sometimes painfully).

**Comment by baywet** [comment]
Love to see the community helping each other!!!
As per the `.User()` suggestion, it's unlikely we'll be adding it anytime soon because of the size challenges as you're aware of.
As per the other things that "don't feel natural" don't hesitate to open new issues to talk about those.
As per the frequent breaking changes, this is intended as long as we're not in GA to make sure we get it right, and feedback like this helps a lot!

**Comment by mblaschke** [comment]
Then this issue can be closed.
For the "don't feel natural" topics i will create new issue, thanks 🙂
