### ISSUE TITLE
Getting Attachments returns empty array

### ISSUE THREAD

**Issue by ratzrattillo** [microsoftgraph/msgraph-sdk-go#229]
Trying to get the attachments from a Messageable object (Email with attachments) seems to return an empty array.

``` golang
*mail.GetHasAttachments()
```
returns true

However:
``` golang
len(mail.GetAttachments())
```
returns 0

Do you experience the same behavior?

**Comment by dadams39** [comment]
Messages from the data store have a boolean set indicating that an attachment exists. However, the attachment is not sent with the message. This is done to decrease the amount of strain on the general query interface, I believe. One has to run an additional query in order to fetch the attachment from the backstore.

**Comment by ratzrattillo** [comment]
@dadams39 Thanks for your hint. I will try it out as soon as possible. Would it make sense to scrap the "GetAttachments"-Method in my example? I don't see the purpose of its existence then.

**Comment by dadams39** [comment]
I cannot speculate as to what will make *sense* for the code you are creating. However, the results of performing an attachment length query on a `Messageable` object directly from the store currently will not provide any helpful feedback. However, if you are using it as a placeholder to check for `SDK` changes in the future, it perhaps could serve a purpose. 

 ¯\_(ツ)_/¯
