### ISSUE TITLE
Problem getting the right value from GetAdditionalData

### ISSUE THREAD

**Issue by Emmawaterman** [microsoftgraph/msgraph-sdk-go#292]
This is the curl that works for me:
` curl -s -H "Authorization: Bearer $AZ_TOKEN" https://graph.microsoft.com/v1.0/users/<USERID>\?\$select\=id,displayname,mail,extension_githubUserName`
and I am trying to reproduce with the sdk and looking for the `extension_d0b6689599b848618c9a49bfed78abb2_githubUserName` field value specifically, and this is what I did
`extension := result.GetValue()[0].GetAdditionalData()["extension_githubUserName"]`
this only gives me a pointer address and the value changes everytime I run the script. 
I tested with other known field like Get mail, which works fine.
`*result.GetValue()[0].GetMail()`
Anything I am missing here?

**Comment by Emmawaterman** [comment]
I was able to figure this out last night, the return type for the additionalData is a *string, so i have to cast it to (*string) and then dereference it. I wish this is easier to use and hard to understand why the type is *string instead of string because in the curl command response is the same as other user properties.

**Comment by rkodev** [comment]
Hi @Emmawaterman, Thanks for trying out the SDK.
As you figured out, the issue was that you were getting the pointer address and not the value. You do need to dereference the pointer as you correctly did. The reason pointers are preferred in this case is so that the SDK can be conservative with memory allocation.
