### ISSUE TITLE
Identity own permissions

### ISSUE THREAD

**Issue by jkroepke** [microsoftgraph/msgraph-sdk-go#335]
Hi,

i'm currently this SDK with client credential flow. I would like to know if there is a way to identify if certain permissions are granted on that service prinical and if now, then crash.

I tried to put the required API permissions into the scope, but then I got errors that I provide invalid scopes..

Any ideas? For example I have to check, if `SecurityEvents.Read.All` permissions are granted, w/o asking the servicePrincipal roleAssignment API

**Comment by baywet** [comment]
Hi @jkroepke,
Thanks for using the Go SDK and for reaching out.
Are you setting the scope in the authentication provider or using the default scope?
If the scope is set in the authentication provider, and the user doesn't consent to it, the token acquisition would fail, returning an error when using the SDK.
When using the default scope, it relies on whatever has been configured and consented to the application, so you might get a token that has or not the scope you desire.
The easiest is probably to do the former, but in case you need to stick with the later because of other constraints, there's no token introspection endpoint available.
The only alternatives would be to use another app registration to check yours with the authorization APIs or to use a JWT library to "crack open" the access token and inspect which scopes are present.
I hope this helps. Let us know if you have additional questions.

**Comment by jkroepke** [comment]
Hi @baywet ,

since this is a headless service in Kubernetes, there is no user consent with scopes. The App Registration has a pre-granted admin consent.

I have to use the default scope. If I add the permissions trough additional scopes, I got a error like invalid scopes. Feels like thats not supported with Client Credential login.

**Comment by baywet** [comment]
Thanks for the additional information.
In that scenario:
- Your application can only use the default scope when initializing the auth context.
- The only way to know which scopes have been consented to (as far as I know) is to crack open the JWT/access token.
- Scopes will be under the "roles" claim (because app only context, otherwise they'd be under "scp").

Let us know if you need any more help.

**Comment by jkroepke** [comment]
Thanks a lot!
