### ISSUE TITLE
support 'mailboxSettings' in go SDK

### ISSUE THREAD

**Issue by neha-Gupta1** [microsoftgraph/msgraph-sdk-go#464]
Add support for Get- `mailboxSettings` i.e.,
`https://graph.microsoft.com/v1.0/users/<userID>/mailboxSettings` in go SDK

**Comment by rkodev** [comment]
Hi @neha-Gupta1, Thanks for trying the SDK. To answer this shortly, we are not able to directly add request as this Repo is generated via [kiota](https://github.com/microsoft/kiota) and the openapi schema needs to be updated by individual services.

However you can use this workaround to get  mailboxsettings

```go

	query := &users.UserItemRequestBuilderGetQueryParameters{
		//Only request specific properties
		Select: []string{
			"mailboxSettings",
			// bunch of other fields
		},
	}
	options := &users.UserItemRequestBuilderGetRequestConfiguration{QueryParameters: query}

	result, err := client.UsersById("<user-id>").Get(context.Background(), options)

```

**Comment by baywet** [comment]
@rkodev after investigating this further it seems [the conversion mechanism is already implemented](https://github.com/microsoft/OpenAPI.NET.OData/issues/176)

What probably needs to happen for this to work ( `GET /users/id/mailboxSettings` is present as `client.Users().WithId("id").MailboxSettings.Get()`) we'd need to:
1. Check that the `UseRestrictionAnnotationsToGeneratePathsForComplexProperties` setting for OpenAPI profile is unset or set to true.
2. Add an XSLT rule to add the CRUD restrictions annotations for that complex typed property in the metadata.
3. Kick off a generation.

Since there's a workaround for this when reading (select you've just shared), and this is an issue maybe only for updates, it's probably a lower priority than the GA work at this time. Can you:
1. log an issue with the relevant details in the metadata repo.
2. check with @maisarissi and @andrueastman how much this is needed for other SDKs based on customer demand.

Thanks a lot!

**Comment by andrueastman** [comment]
Thanks for this @baywet. Knowing this is really helpful. 

I've authored https://github.com/microsoftgraph/msgraph-metadata/pull/324 to close this as there is also a similar/related issue in dotnet.

> @rkodev after investigating this further it seems [the conversion mechanism is already implemented](https://github.com/microsoft/OpenAPI.NET.OData/issues/176)

**Comment by neha-Gupta1** [comment]
> Hi @neha-Gupta1, Thanks for trying the SDK. To answer this shortly, we are not able to directly add request as this Repo is generated via [kiota](https://github.com/microsoft/kiota) and the openapi schema needs to be updated by service owners.
> 
> However, you can use this workaround to get mailbox settings
> 
> ```go
> 	query := &users.UserItemRequestBuilderGetQueryParameters{
> 		//Only request specific properties
> 		Select: []string{
> 			"mailboxSettings",
> 			// bunch of other fields
> 		},
> 	}
> 	options := &users.UserItemRequestBuilderGetRequestConfiguration{QueryParameters: query}
> 
> 	result, err := client.UsersById("<user-id>").Get(context.Background(), options)
> ```



@rkodev I tried it. But it gave me a `nil` result. I have figured out a workaround for it as,

```go
var (
		rawURL  = fmt.Sprintf("https://graph.microsoft.com/v1.0/users/%s/mailboxSettings", userID)
		adapter = c.stable.Adapter()
		builder = users.NewUserItemRequestBuilder(rawURL, adapter)
	)

newItem, err := builder.Get(ctx, nil)
purpose := *(newItem.GetAdditionalData()(*string))

```
