### ISSUE TITLE
Nil Messageable Interfaces

### ISSUE THREAD

**Issue by ali-siddiqi** [microsoftgraph/msgraph-sdk-go#528]
Is it expected that the interfaces returned by a `Messageable` would be nil?

Currently we are attempting to parse fields from a `Messageable` via functions like `GetSender()`, `GetEmailAddress()`, and `GetBody()`. However, it appears we need to do nil checks on each of the values returned by these functions, rather than only on the pointer return values.

**Comment by baywet** [comment]
Hi @ali-siddiqi 
Thanks for reaching out and for using the SDK.
Yes, it's a design decision since you can (should) select or not each field of type using a select query parameter.
Also the value for some properties can outright be null on the service side/in the payload.
For those reasons we're projecting nillable types in the properties and your application should check the values before trying to use them.
Let us know if you have further questions.

**Comment by ali-siddiqi** [comment]
No further questions, that clears it up. Thank you!
