### ISSUE TITLE
is it possible to rename the "external" package to another name?

### ISSUE THREAD

**Issue by andyliuliming** [microsoftgraph/msgraph-sdk-go#545]
this naming does not work on the project using bazel to build.

because "external" is a reserved key in bazel.

**Comment by rkodev** [comment]
Hi @andyliuliming it is not possible to rename the packages in this case because while `external` is a reserved name is bazel this is not a reservation native to Go language itself.  It might be possible to resolve the issue with a configuration of bazel itself as opposed to renaming the package itself.

It would not be possible to avoid all the names that are key words not native to the Go itself and I suggest considering using the second approach of tweaking the build tool slightly

**Comment by bozaro** [comment]
This problem can be worked around with a patch:

```bazel
    go_repository(
        name = "com_github_microsoftgraph_msgraph_sdk_go",
        importpath = "github.com/microsoftgraph/msgraph-sdk-go",
        patches = ["//thirdparty/com_github_microsoftgraph_msgraph_sdk_go:com_github_microsoftgraph_msgraph_sdk_go.patch"],
        ...
    )
```

thirdparty/com_github_microsoftgraph_msgraph_sdk_go/com_github_microsoftgraph_msgraph_sdk_go.patch:
```patch
diff -urN orig/BUILD.bazel need/BUILD.bazel
--- BUILD.bazel
+++ BUILD.bazel
@@ -44,7 +44,7 @@
         "//drives",
         "//education",
         "//employeeexperience",
-        "//external",
+        "@com_github_microsoftgraph_msgraph_sdk_go//external",
         "//filteroperators",
         "//functions",
         "//grouplifecyclepolicies",
```
