### ISSUE TITLE
Does the client auto refresh bearer tokens?

### ISSUE THREAD

**Issue by eric-millin** [microsoftgraph/msgraph-sdk-go#595]
Is there a mechanism that refreshes or fetches a new auth token periodically to prevent expiration? I took a cursory walk thru the code and it wasn't immediately apparent.

**Comment by baywet** [comment]
Hi @eric-millin 
Thanks for using the Go SDK and for reaching out.
The Microsoft Graph SDK [requests an access token to Azure Identity](https://github.com/microsoft/kiota-authentication-azure-go/blob/158857c60fbfeaece9bec28c8d12aa1ee52687d7/azure_identity_access_token_provider.go#L77) for every request.
Then, depending on the credentials / flow in use, the token might already be cached locally or not.
When it's not cached locally, it effectively gets requested to the identity service every time, and can't be expired (besides some clock issues, but that's beyond the point).
When it's cached locally, the cached token may be expired, and depending on the flow, Azure Identity may refresh the token under the hood (transparent, besides extra latency), prompt the user to sign in again, or fail all together returning an exception.

[Only the Azure CLI credential](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#AzureCLICredential.GetToken) documents the fact that it DOES NOT cache tokens, IMHO every credential should document this aspect.
The best way forward is probably to open a new issue on [Azure/azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go) to ask for clarifications here.

Closing since there not much more to be done in the Microsoft Graph SDK.

**Comment by Turkish** [comment]
@baywet When the application is closed , the internal cache goes away. This means every time the user opens the application after closing it, he would need to authenticate via browser.  There is no persistence of refresh token handled by the SDK, and the SDK is not exposing the refresh token for us to store and use. This forces us to shortcut the SDK and query the API directly to get the refresh token. Am I missing something ?

**Comment by baywet** [comment]
Hi @Turkish 
The SDK relies on Azure Identity to perform the authentication work.
Any question about authentication, cache persistence/hydration, etc... Should be [asked on the azure repository](https://github.com/microsoft/kiota-authentication-azure-go/) to get answers from the right experts.
