### ISSUE TITLE
Feature Request: tenant level user settings API is not available in msgraph sdk nor in beta sdk

### ISSUE THREAD

**Issue by lchavan-uptycs** [microsoftgraph/msgraph-sdk-go#611]
Feature Request:
- MSGraph SDK used: http://github.com/microsoftgraph/msgraph-sdk-go v1.14.0
- MSGraphBeta SDK used: http://github.com/microsoftgraph/msgraph-beta-sdk-go  v0.78.0
- In User didn't find a method to list all tenant-level user settings, configurable on the path: [Home > Microsoft Entra ID > Users > User settings](https://portal.azure.com/#view/Microsoft_AAD_UsersAndTenants/UserManagementMenuBlade/~/UserSettings)

**Comment by baywet** [comment]
Hi @lchavan-uptycs 
Thanks for using the Go SDK and for reaching out.
This SDK is generated from service metadata provided by the API owners.
If a property is missing, it's most likely because the API hasn't implemented it yet, or they didn't update the metadata to reflect it.
The API owners are not watching this repository, the best thing to reach out to them is to [ask a question with the dedicated Azure AD API tag in Microsoft Q&A](https://learn.microsoft.com/en-us/answers/tags/302/microsoft-graph-azure-ad-api/)

**Comment by lchavan-uptycs** [comment]
Hi @baywet 
Ok, I will ask question on that thread 

Thanks!!
