### ISSUE TITLE
Persist Successful Device Grant Flow Login 

### ISSUE THREAD

**Issue by androakimoto** [microsoftgraph/msgraph-sdk-go#644]
Hi,

i am trying out [Build Go apps with Microsoft Graph](https://learn.microsoft.com/en-us/graph/tutorials/go?tabs=aad). I want to write a cli using the device grant flow from the cli. So based on this tutorial, everything works fine. Flow is initiated, and then i can retrieve data from azure. 

Problem: Every time when i start the tutorial program a new device grant flow is initiated.

Question: Is there a way to persist an successful login also when program is finished? (So that I don't have to restart this login every time I start it)

Any idea?

Many Thanks and Cheers!

**Comment by baywet** [comment]
Hi @androakimoto
Thanks for using the Go SDK and for reaching out.
The SDK relies on Azure Identity for authentication concerns to provide a unified experience when application are integrated with Microsoft Graph or Azure APIs.
Since this is an authentication specific question, I'll encourage you to [ask it on the azure sdk repository](https://github.com/Azure/azure-sdk-for-go) where you'll get answers directly from the team that built that library.
Closing
