### ISSUE TITLE
Panic while parsing weird email address

### ISSUE THREAD

**Issue by drummonds** [microsoftgraph/msgraph-sdk-go#674]
I have received some I think mailicious email but the from field (from Outlook message details was:

From: =?UTF-8?B?=RHJ1bW1vbmRzIEhSIC0gU2hhcmVkIHZpYSBPbmxpbmVEb2Nz?= ,------_------<postmaster@mmolaw.com>

This caused the address to panic.

	this_message := message.GetFrom()
	this_email := this_message.GetEmailAddress()
	address := *this_email.GetAddress()

In the mean time will just recover and then process appropriately

**Comment by rkodev** [comment]
@drummonds from the given snippet it looks like address field might be a nil value. To be certain however please share the json value from the server. I'd like to be sure that this is not a serialization issue.

In the meantime, if the address field is a nil value you might want to check it instead of catching the panic i.e

```go
address  := this_email.GetAddress()
if address  != nil {
    // process address  
}
```
