### ISSUE TITLE
When paginating over groups, some groups are skipped when specifying an OrderBy Clause

### ISSUE THREAD

**Issue by matt-tyler-qoria** [microsoftgraph/msgraph-sdk-go#784]
### Describe the bug

I  attempted to paginate over a very large number of groups using an iterator.

e.g.

```
func MakeGroupIterator(ctx context.Context, client *msgraphsdk.GraphServiceClient) (Iterator[*models.Group], error) {
	result, err := client.Groups().Get(ctx, &groups.GroupsRequestBuilderGetRequestConfiguration{
		QueryParameters: &groups.GroupsRequestBuilderGetQueryParameters{
			Orderby: []string{"displayName"},
			Select:  []string{"displayName", "description", "id", "objectId", "visibility"},
		},
	})
	if err != nil {
		return nil, err
	}

	it, err := msgraphcore.NewPageIterator[*models.Group](result, client.GetAdapter(), models.CreateGroupCollectionResponseFromDiscriminatorValue)
	if err != nil {
		return nil, err
	}
	return it.Iterate, nil
}
```

However, I've noticed its not functioning correctly when ordering by display name. It skips over entire ranges and as such there are groups missing from the complete collection - as if its using the last ID to fetch a page, as opposed to the displayName.

If I do not specify the Orderby parameter, everything works correctly.

The entire collection consists of approximately 260,000 groups. When using Orderby, there were roughly 30,000 groups missing.

I'm unsure as to whether this is an issue with the SDK, or with the graph service itself.

I could this being perfectly reasonably behaviour but I was unable to find it documented anywhere.

### Expected behavior

All groups are returned via pagination, regardless of the orderby clause

OR

there is some warning somewhere that pagination does not function correctly when specifying an orderby clause.

### How to reproduce

Paginate over a group set as above.

I'm unsure as to level of the data that would be required for this to be noticeable.

### SDK Version

 v1.43.0

### Known Workarounds

Do not specify an orderby clause when attempting to paginate through a full set of groups.

### Debug output

NA

### Configuration

Mac OS / ARM 64
Debian x64

**Comment by rkodev** [comment]
Hi @matt-tyler-qoria , Thanks for trying out the GO SDK. This looks like a service layer issue and not an SDK issue, the SDK uses an endpoint returned by the service, as seen [here](https://github.com/microsoftgraph/msgraph-sdk-go-core/blob/3f4ae7849f85bf6236277a86ec28b153d67804df/page_iterator.go#L158), to iterate over the pages.

For now, I'd suggests fetching the collection locally and sorting them after fetching them, also could you kindly report this bug here on [Microsoft QnA](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) so the relevant team can address is
